name: fern-check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [docs-starter, i18n, versioning]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fern CLI
        uses: fern-api/setup-fern-cli@v1

      - name: Check API is valid
        working-directory: ${{ matrix.project }}
        run: fern check
