name: publish-docs

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/main') && github.run_number > 1 }}
    strategy:
      fail-fast: false
      matrix:
        project: [docs-starter, i18n, multi-source/seeds, multi-source/greenhouses, multi-source/nursery, versioning]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fern CLI
        uses: fern-api/setup-fern-cli@v1

      - name: Publish Docs
        working-directory: ${{ matrix.project }}
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --docs --log-level debug
